version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: tail -f /dev/null
    container_name: bot-editor-app
    volumes:
      - ../../.:/app
